import React, { useState, useEffect } from "react";
import Link from 'next/link';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import { useRouter } from 'next/router'
import { BrowserRouter, Routes, Route, NavLink, useLocation } from "react-router-dom";

const Home = () => { return <p>Home</p> }
const Login = () => { return <p>Login</p> }
const RecoveryPassword = () => { return <p>RecoveryPassword</p> }
const NotFound = () => {
  const router = useRouter();
  let location = useLocation();
  //console.log(router);
  console.log(location);
  if (location.pathname === '/customer-care') {
    return ''; // default
  } else {
    window.location.href = location.pathname;
  }
}

const SPA = () => {
  return (<>
    <BrowserRouter>
      <ul>
        {/* 点击跳转 Link  NavLink */}
        <NavLink to="/spa" activestyle={{ color: '#f66' }}>首页</NavLink> |
        <NavLink to="/login" activestyle={{ color: '#f66' }}> 登录</NavLink> |
        <NavLink to="/recovery-password" activestyle={{ color: '#f66' }}> 恢复密码</NavLink> |
        <NavLink to="/fgm" activestyle={{ color: '#f66' }}> FGM - 模块跳转</NavLink>
      </ul>
      <Routes>
        <Route exact path="/spa" element={<Home />} />
        <Route exact path="/login" element={<Login />} />
        <Route exact path="/recovery-password" element={<RecoveryPassword />} />
        <Route path="*" element={<NotFound />} />
      </Routes>
    </BrowserRouter>
  </>)
}

export default function CC({ tags }) {
  const [inBrowser, setInBrowser] = useState(false);
  const [userName, setUserName] = useState('noname');

  useEffect((tags) => {
    console.log('componentDidMount');
    const name = localStorage.getItem('myCat');
    if (name === null) {
      name = 'Tom'
      localStorage.setItem('myCat', name);
      console.log('set Name', name);
    }

    setUserName(name);
    setInBrowser(true);
  }, []);




  return (
    <div className={styles.container}>
      <Head>
        <title>Customer Care</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href='/'>Link 返回主页</Link>
        <a href='/'>a 返回主页</a>
        <h1 className={styles.title}>
          Customer Care
        </h1>
        <div>
          {inBrowser && tags.map(item => <span className={styles.tag} key={item.id}>{item.tag}</span>)}
        </div>
        <p>
          Name: {userName}
        </p>

        <div>
          {inBrowser && <SPA />}
        </div>

      </main>

    </div>
  )
}

export async function getServerSideProps(context) {
  let tags = [1, 2, 3];

  tags = await axios.get('http://www.tomtalk.net/tag_api/getListTotal').then(res => {
    return res.data;
  });

  return {
    props: {
      tags: tags
    }
  }
}