import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { Divider, Stack } from '@chakra-ui/react'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}> Learn <a href="https://nextjs.org">Next.js!</a> </h1>

        <Divider m="2em 0px" />

        <Stack>
          <p>1. Link组件跳转，保持SPA特性，仅加载增量内容。</p>
          <p className={styles.normal}><Link href="/customer-care" ><a>Customer Care</a></Link></p>

          <p>2. 普通a标签跳转，全量加载页面内容。</p>
          <p className={styles.normal}><a href="/customer-care">Customer Care</a></p>
        </Stack>

      </main>
    </div>
  )
}
