import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { Divider, Stack } from '@chakra-ui/react'

export default function Home({ time }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}> Learn <a href="https://nextjs.org">Next.js!</a> </h1>

        <Divider m="2em 0px" />

        <Stack>
          <p>1. Link组件跳转，保持SPA特性，仅加载增量内容。</p>
          <p className={styles.normal}><Link href="/customer-care" ><a>Customer Care</a></Link></p>

          <p>2. 普通a标签跳转，全量加载页面内容。</p>
          <p className={styles.normal}><Link href="/customer-care">Customer Care</Link></p>
        </Stack>

        <h1 className={styles.title}>SSR Caching with Next.js</h1>
        <Divider m="2em 0px" />
        <time dateTime={time}>{time}</time>
        <Divider m="2em 0px" />
        <p className={styles.normal}><Link href="/call-us">Call Us</Link></p>
      </main>
    </div>
  )
}

export async function getServerSideProps({ req, res }) {
  res.setHeader(
    'Cache-Control',
    'public, s-maxage=10, stale-while-revalidate=59'
  )

  console.log('getServerSideProps()');

  return {
    props: {
      time: new Date().toISOString(),
    },
  }
}
