import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { Divider, Stack, Box } from '@chakra-ui/react'
import Heading from '../components/heading'

export default function Home({ time }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading>
          Learn <a href="https://nextjs.org">Next.js!</a>
        </Heading>

        <Divider m="1em 0px" />

        <Stack>
          <p>1. Link组件跳转，保持SPA特性，仅加载增量内容。</p>
          <p className={styles.normal}><Link href="/customer-care" >Customer Care</Link></p>

          <p>2. 普通a标签跳转，全量加载页面内容。</p>
          <p className={styles.normal}><a href="/customer-care">Customer Care</a></p>
        </Stack>

        <Box h="3em" />

        <Heading>SSR Caching with Next.js</Heading>

        <Divider m="1em 0px" />

        <time dateTime={time}>{time}</time>

        <Box h="3em" />

        <Heading mt="32px">Reduce vendor.js size</Heading>

        <Divider m="1em 0px" />

        <p className={styles.normal}><Link href="/call-us">Call Us</Link></p>

        <Divider m="1em 0px" />
      </main>

      <Heading mt="32px"> Footer Covered on Iphone</Heading>

      <Box h="25em" />

      <Box bg="#f6f6f6" p="0.5em" textAlign='center'>Footer Bar</Box>
    </div>
  )
}

export async function getServerSideProps({ req, res }) {
  res.setHeader(
    'Cache-Control',
    'public, s-maxage=10, stale-while-revalidate=59'
  )

  return {
    props: {
      time: new Date().toISOString(),
    },
  }
}
